language: java

env:
   - secure: "kxZcTdRqGMF3To5ZMbY5YYJgzdz5/hd/HnL3WxX5qRXF2kGMReLWKc+720VFDqH9SG6Jp7cvftF4\
V8pz7qB9XOAM3nEwMgueDV9ic8x90Gf7+Wfa5cUAb7QHh/fGYshtkpo4vhga2gs3vVnKzG+mcO2O\
juYvSxjsGLno4GnPw/21MYDWHY8BbW4L9I77dpZVSw+KBgpywBlItHxODwgivoOwXRgpsmtpR22h\
OQKHrta8WYyV/bF+c4ad5/jbbk2sDmwiiwyNYnjhsH9a2zkxXeqmBA/p1Vh8hEgGQwxw1BIIkgDn\
aK2ayd4A59vD0iOzc0qThNz78nha843hH7wjwfgEtDZuBJjJOpYtvkNu3AuE71nkDmJJx/6J/GfA\
748b1KgIyx8O2SmXeJ+mEQENxRCuxwn0qz3kxBWeR41H1hItkle6yOABALtl0O4eFrdKiXi+FldI\
UHsM9cDr8QQRHIxeCO+kFGxCGLcqDhY+zmfhUiiIOinyRP8ozFaUOnDLcoQJ5HcpMl64YRdtCMuf\
CBoN03HcWzWF1tiBz4RffegABLn+kd0zYDAYR83iFCqnnD5raYWGbOmaTzBZfeF1wiGWMZd8zhg3\
NEwDInU3zPyE+2PLZjHuufdhrjQvEeFOBcRNyGd29Tm3dWCict5Si/NPOe5vrd7VZK/h8njBk+s=\
   "

before_install:
- ./etc/before.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./etc/deploy.sh
  on:
    branch: master
