language: java

env:
  global:
   - secure: "OC/u6HECJWiKj/cakwM09iTdYRw9TY2wJ4OW+UELIyTKMNkRGuupPfx3LpgEz5aKF3/Ce7aTSZqgglYJm2Jzip2Wqo+mdjXa1qvh88bYcsdtWsac+SfkfxrlYZKGWbV5cmJSWCB5xBFe4/Tbv7T4Y89fFaDQ65fgSko0DxCOKBY="

before_install:
- ./etc/before.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./etc/deploy.sh
  on:
    branch: master
